
import Head from 'next/head'
import CustomerLogos from '../components/CustomerLogos'
import Products from '../components/Products'
import Footer from '../components/Footer'
import Header from '../components/Header'
import Hero from '../components/Hero'
import About from '../components/About'
import Contact from '../components/Contact'
import Testimonials from '../components/Testimonials'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Chitaitai</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/firefly.png" />
      </Head>

      <Header />
      <Hero />
      <About />
      <CustomerLogos />
      <Products />
      <Testimonials />
      <Contact />
      <Footer />

        
              
      
    </div>
  )
}
